<?php

namespace ListBundle\Repository;

/**
 * ListItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListItemRepository extends \Doctrine\ORM\EntityRepository
{
}
